import 'package:flutter_test/flutter_test.dart';
import 'package:number_to_text_converter/number_to_text_converter.dart';

void main() {
  var converter = NumberToTextConverter.forIndianNumberingSystem();

  test('indian numbering system number conversion', () {
    expect(converter.getTextForNumber(0), '');
    expect(converter.getTextForNumber(1), 'one');
    expect(converter.getTextForNumber(2), 'two');
    expect(converter.getTextForNumber(3), 'three');
    expect(converter.getTextForNumber(4), 'four');
    expect(converter.getTextForNumber(5), 'five');
    expect(converter.getTextForNumber(6), 'six');
    expect(converter.getTextForNumber(7), 'seven');
    expect(converter.getTextForNumber(8), 'eight');
    expect(converter.getTextForNumber(9), 'nine');
    expect(converter.getTextForNumber(10), 'ten');
    expect(converter.getTextForNumber(11), 'eleven');
    expect(converter.getTextForNumber(12), 'twelve');
    expect(converter.getTextForNumber(13), 'thirteen');
    expect(converter.getTextForNumber(14), 'fourteen');
    expect(converter.getTextForNumber(15), 'fifteen');
    expect(converter.getTextForNumber(16), 'sixteen');
    expect(converter.getTextForNumber(17), 'seventeen');
    expect(converter.getTextForNumber(18), 'eighteen');
    expect(converter.getTextForNumber(19), 'nineteen');
    expect(converter.getTextForNumber(20), 'twenty');
    expect(converter.getTextForNumber(21), 'twenty one');
    expect(converter.getTextForNumber(22), 'twenty two');
    expect(converter.getTextForNumber(23), 'twenty three');
    expect(converter.getTextForNumber(24), 'twenty four');
    expect(converter.getTextForNumber(25), 'twenty five');
    expect(converter.getTextForNumber(26), 'twenty six');
    expect(converter.getTextForNumber(27), 'twenty seven');
    expect(converter.getTextForNumber(28), 'twenty eight');
    expect(converter.getTextForNumber(29), 'twenty nine');
    expect(converter.getTextForNumber(30), 'thirty');
    expect(converter.getTextForNumber(33), 'thirty three');
    expect(converter.getTextForNumber(38), 'thirty eight');
    expect(converter.getTextForNumber(40), 'forty');
    expect(converter.getTextForNumber(50), 'fifty');
    expect(converter.getTextForNumber(60), 'sixty');
    expect(converter.getTextForNumber(70), 'seventy');
    expect(converter.getTextForNumber(80), 'eighty');
    expect(converter.getTextForNumber(90), 'ninety');
    expect(converter.getTextForNumber(99), 'ninety nine');
    expect(converter.getTextForNumber(100), 'one hundred');
    expect(converter.getTextForNumber(101), 'one hundred and one');
    expect(converter.getTextForNumber(102), 'one hundred and two');
    expect(converter.getTextForNumber(103), 'one hundred and three');
    expect(converter.getTextForNumber(104), 'one hundred and four');
    expect(converter.getTextForNumber(105), 'one hundred and five');
    expect(converter.getTextForNumber(106), 'one hundred and six');
    expect(converter.getTextForNumber(107), 'one hundred and seven');
    expect(converter.getTextForNumber(108), 'one hundred and eight');
    expect(converter.getTextForNumber(109), 'one hundred and nine');
    expect(converter.getTextForNumber(110), 'one hundred and ten');
    expect(converter.getTextForNumber(111), 'one hundred and eleven');
    expect(converter.getTextForNumber(115), 'one hundred and fifteen');
    expect(converter.getTextForNumber(119), 'one hundred and nineteen');
    expect(converter.getTextForNumber(120), 'one hundred and twenty');
    expect(converter.getTextForNumber(124), 'one hundred and twenty four');
    expect(converter.getTextForNumber(129), 'one hundred and twenty nine');
    expect(converter.getTextForNumber(130), 'one hundred and thirty');
    expect(converter.getTextForNumber(140), 'one hundred and forty');
    expect(converter.getTextForNumber(150), 'one hundred and fifty');
    expect(converter.getTextForNumber(160), 'one hundred and sixty');
    expect(converter.getTextForNumber(170), 'one hundred and seventy');
    expect(converter.getTextForNumber(180), 'one hundred and eighty');
    expect(converter.getTextForNumber(190), 'one hundred and ninety');
    expect(converter.getTextForNumber(199), 'one hundred and ninety nine');
    expect(converter.getTextForNumber(200), 'two hundred');
    expect(converter.getTextForNumber(300), 'three hundred');
    expect(converter.getTextForNumber(400), 'four hundred');
    expect(converter.getTextForNumber(500), 'five hundred');
    expect(converter.getTextForNumber(600), 'six hundred');
    expect(converter.getTextForNumber(700), 'seven hundred');
    expect(converter.getTextForNumber(800), 'eight hundred');
    expect(converter.getTextForNumber(900), 'nine hundred');
    expect(converter.getTextForNumber(1000), 'one thousand');
    expect(converter.getTextForNumber(1001), 'one thousand one');
    expect(converter.getTextForNumber(1005), 'one thousand five');
    expect(converter.getTextForNumber(1010), 'one thousand ten');
    expect(converter.getTextForNumber(1012), 'one thousand twelve');
    expect(converter.getTextForNumber(1020), 'one thousand twenty');
    expect(converter.getTextForNumber(1081), 'one thousand eighty one');
    expect(converter.getTextForNumber(1099), 'one thousand ninety nine');
    expect(converter.getTextForNumber(1100), 'one thousand one hundred');
    expect(converter.getTextForNumber(1101), 'one thousand one hundred and one');
    expect(converter.getTextForNumber(1110), 'one thousand one hundred and ten');
    expect(converter.getTextForNumber(1115), 'one thousand one hundred and fifteen');
    expect(converter.getTextForNumber(1120), 'one thousand one hundred and twenty');
    expect(converter.getTextForNumber(1124), 'one thousand one hundred and twenty four');
    expect(converter.getTextForNumber(1150), 'one thousand one hundred and fifty');
    expect(converter.getTextForNumber(1199), 'one thousand one hundred and ninety nine');
    expect(converter.getTextForNumber(1200), 'one thousand two hundred');
    expect(converter.getTextForNumber(1300), 'one thousand three hundred');
    expect(converter.getTextForNumber(1400), 'one thousand four hundred');
    expect(converter.getTextForNumber(1500), 'one thousand five hundred');
    expect(converter.getTextForNumber(1600), 'one thousand six hundred');
    expect(converter.getTextForNumber(1700), 'one thousand seven hundred');
    expect(converter.getTextForNumber(1800), 'one thousand eight hundred');
    expect(converter.getTextForNumber(1900), 'one thousand nine hundred');
    expect(converter.getTextForNumber(1999), 'one thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(2000), 'two thousand');
    expect(converter.getTextForNumber(2562), 'two thousand five hundred and sixty two');
    expect(converter.getTextForNumber(3000), 'three thousand');
    expect(converter.getTextForNumber(4000), 'four thousand');
    expect(converter.getTextForNumber(5000), 'five thousand');
    expect(converter.getTextForNumber(6000), 'six thousand');
    expect(converter.getTextForNumber(7000), 'seven thousand');
    expect(converter.getTextForNumber(8000), 'eight thousand');
    expect(converter.getTextForNumber(9000), 'nine thousand');
    expect(converter.getTextForNumber(9999), 'nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(10000), 'ten thousand');
    expect(converter.getTextForNumber(10001), 'ten thousand one');
    expect(converter.getTextForNumber(10010), 'ten thousand ten');
    expect(converter.getTextForNumber(10011), 'ten thousand eleven');
    expect(converter.getTextForNumber(10083), 'ten thousand eighty three');
    expect(converter.getTextForNumber(10100), 'ten thousand one hundred');
    expect(converter.getTextForNumber(10500), 'ten thousand five hundred');
    expect(converter.getTextForNumber(10999), 'ten thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(11000), 'eleven thousand');
    expect(converter.getTextForNumber(11378), 'eleven thousand three hundred and seventy eight');
    expect(converter.getTextForNumber(20000), 'twenty thousand');
    expect(converter.getTextForNumber(68723), 'sixty eight thousand seven hundred and twenty three');
    expect(converter.getTextForNumber(99999), 'ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(100000), 'one lakh');
    expect(converter.getTextForNumber(100001), 'one lakh one');
    expect(converter.getTextForNumber(100010), 'one lakh ten');
    expect(converter.getTextForNumber(100013), 'one lakh thirteen');
    expect(converter.getTextForNumber(100024), 'one lakh twenty four');
    expect(converter.getTextForNumber(100100), 'one lakh one hundred');
    expect(converter.getTextForNumber(100111), 'one lakh one hundred and eleven');
    expect(converter.getTextForNumber(102111), 'one lakh two thousand one hundred and eleven');
    expect(converter.getTextForNumber(111111), 'one lakh eleven thousand one hundred and eleven');
    expect(converter.getTextForNumber(199999), 'one lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(200000), 'two lakh');
    expect(converter.getTextForNumber(222222), 'two lakh twenty two thousand two hundred and twenty two');
    expect(converter.getTextForNumber(900000), 'nine lakh');
    expect(converter.getTextForNumber(999999), 'nine lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(1000000), 'ten lakh');
    expect(converter.getTextForNumber(1000001), 'ten lakh one');
    expect(converter.getTextForNumber(1252212), 'twelve lakh fifty two thousand two hundred and twelve');
    expect(converter.getTextForNumber(9999999), 'ninety nine lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(10000000), 'one crore');
    expect(converter.getTextForNumber(10000001), 'one crore one');
    expect(converter.getTextForNumber(10000119), 'one crore one hundred and nineteen');
    expect(converter.getTextForNumber(15334564),
        'one crore fifty three lakh thirty four thousand five hundred and sixty four');
    expect(converter.getTextForNumber(19999999),
        'one crore ninety nine lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(20000000), 'two crore');
    expect(converter.getTextForNumber(100000000), 'ten crore');
    expect(converter.getTextForNumber(999999999),
        'ninety nine crore ninety nine lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(1000000000), 'one hundred crore');
    expect(converter.getTextForNumber(1000000001), 'one hundred crore one');
    expect(converter.getTextForNumber(1554488392),
        'one hundred and fifty five crore forty four lakh eighty eight thousand three hundred and ninety two');
    expect(converter.getTextForNumber(9999999999),
        'nine hundred and ninety nine crore ninety nine lakh ninety nine thousand nine hundred and ninety nine');
    expect(converter.getTextForNumber(10000000000), 'one thousand crore');
    expect(converter.getTextForNumber(13000000000), 'one thousand three hundred crore');
    expect(converter.getTextForNumber(135000000000), 'thirteen thousand five hundred crore');
    expect(
        converter.getTextForNumber(4121421211155596001),
        'forty one thousand two hundred and fourteen crore '
        'twenty one lakh twenty one thousand one hundred and fifteen crore '
        'fifty five lakh ninety six thousand one');
  });
}
