name: number_to_text_converter
description: A library to convert a number to its text representation as per the International or Indian Numbering System
version: 1.0.6
homepage: https://github.com/ShoutOutSoftware/NumberToTextConverter-Dart

environment:
  sdk: ">=2.17.0 <3.16.19"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter